add homework
kristina-oleinikova/AQAcourse pull request #1
Opened 2023-06-24 22:16 UTC by kristina-oleinikova

please, review homework tast. I faced problems with group annotation (don't know why it doesn't work for me)

2023-06-26 15:10 UTC, wildpioneer requested changes

2023-06-26 15:10 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int divInt(int a, int b){
Почему названия методов имеют разные названия?
Повторить перегрузку методов

2023-06-26 15:10 UTC, wildpioneer commented on src/test/java/HomeWork.java
> +    @Test(groups = "regression", testName = "Divide by Zero Double")
Отсутствуют следующие тесты:

1. expectedExceptions
2. @Parameters
3. retryAnalyzer
4. Double.NaN
5. Double.NEGATIVE_INFINITY
6. Double.POSITIVE_INFINITY

2023-07-02 12:19 UTC, kristina-oleinikova commented on src/main/java/Calculator.java
> +    public int divInt(int a, int b){
fixed

2023-07-02 12:19 UTC, kristina-oleinikova commented on src/test/java/HomeWork.java
> +    @Test(groups = "regression", testName = "Divide by Zero Double")
1,2,4,5 - fixed
3 - don't fully understand how it works & implement in tests

2023-07-02 12:19 UTC, kristina-oleinikova commented on src/test/java/HomeWork.java
> +    @Test(groups = "regression", testName = "Divide by Zero Double")
point 6 is fixed as well

2023-07-03 20:21 UTC, wildpioneer commented
Проверено

2023-07-03 20:21 UTC, closed without merging