<Selenide> homework
kristina-oleinikova/AQAcourse pull request #10
Opened 2023-08-20 12:03 UTC by kristina-oleinikova

2023-08-28 11:03 UTC, wildpioneer requested changes

2023-08-28 11:03 UTC, wildpioneer commented on src/test/java/tests/LoginTest.java
> +        loginStep.successLogin(user).isPageOpened());
Здесь ошибка - лишняя скобка - и поэтому тесты на запускаются

2023-08-28 11:03 UTC, wildpioneer commented on src/test/java/baseEntities/BaseTest.java
> +    static Logger logger = Logger.getLogger(BaseTest.class);
У меня почему-то не импортируется класс org.apache.log4j.Logger;
и следовательно выдает ошибку

2023-08-28 14:46 UTC, kristina-oleinikova commented on src/test/java/tests/LoginTest.java
> +        loginStep.successLogin(user).isPageOpened());
fixed

2023-08-28 14:46 UTC, kristina-oleinikova commented on src/test/java/baseEntities/BaseTest.java
> +    static Logger logger = Logger.getLogger(BaseTest.class);
fixed

2023-09-04 13:26 UTC, wildpioneer commented
Проверено

2023-09-04 13:26 UTC, closed without merging