add homework
kristina-oleinikova/AQAcourse pull request #3
Opened 2023-07-22 15:01 UTC by kristina-oleinikova

2023-07-23 13:09 UTC, wildpioneer requested changes

2023-07-23 13:09 UTC, wildpioneer commented on src/test/java/LocatorsHomework.java
> +        //Assert.assertTrue(driver.findElement(By.xpath("//*[@class=\"dialog-title\"]/preceding::form")).isDisplayed());
??? А почему эти закоментированы?

2023-07-23 17:51 UTC, kristina-oleinikova commented on src/test/java/LocatorsHomework.java
> +        //Assert.assertTrue(driver.findElement(By.xpath("//*[@class=\"dialog-title\"]/preceding::form")).isDisplayed());
на тот момент, как-то не очень "переваривалась" информация по этому разделу.
немножко больше удалось разобраться - раскомментила и добавила примеры

2023-08-02 08:28 UTC, wildpioneer commented
Проверено

2023-08-02 08:28 UTC, closed without merging