<Wrappers> homework
kristina-oleinikova/AQAcourse pull request #7
Opened 2023-08-09 19:23 UTC by kristina-oleinikova

2023-08-14 08:59 UTC, wildpioneer requested changes

2023-08-14 08:59 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        if(!uiElement.isSelected()){
Замечание: строки 19,20 и 25,26 практически дубликаты - а следовательно нужно вынести в отдельный приватный метод и его уже использовать

2023-08-14 08:59 UTC, wildpioneer commented on src/test/java/elements/Dropdown.java
> +    public void select(){
Идейно данная обертка реализована не верно.
1. У тебя нет методов выбора произвольных элементов
2. ты почему-то работаешь только с select элементами - а это просто существующая уже обертка Select

2023-08-14 08:59 UTC, wildpioneer commented on src/test/java/elements/GroupOfRadioButtons.java
> +public class GroupOfRadioButtons {
Название класса не корректно - основываясь на этом названии, это элемент который работает с группой radioButtons, но при этом реализация говорит об работе с каким-то одиночным radioButton

2023-08-15 18:53 UTC, kristina-oleinikova commented on src/test/java/elements/CheckBox.java
> +        if(!uiElement.isSelected()){
fixed

2023-08-15 18:53 UTC, kristina-oleinikova commented on src/test/java/elements/GroupOfRadioButtons.java
> +public class GroupOfRadioButtons {
fixed

2023-08-15 18:54 UTC, kristina-oleinikova commented on src/test/java/elements/Dropdown.java
> +    public void select(){
не знаю, как тогда переделать 
лучший вариант - использовать твою реализацию

2023-08-28 15:12 UTC, wildpioneer commented
Проверено

2023-08-28 15:12 UTC, closed without merging